#!/bin/sh
if [[ $CIRCLE_BRANCH =~ 'master' ]]; then
	echo 'production'
elif [[ $CIRCLE_BRANCH =~ 'staging' ]]; then
	echo 'staging'
  FILE=.env
  touch $FILE
  echo "ASSET_HOST=$public_ip" >> $FILE
  echo "PGHOST=$db_address" >> $FILE
  echo "PG_PORT=$db_port" >> $FILE
  echo "NGINX_PORT=80" >> $FILE
  echo "HTTPS_NGINX_PORT=443" >> $FILE
  echo "APP_HOST=staging.uleague.org" >> $FILE
  echo "RAILS_ENV=staging" >> $FILE
  echo "REDIS_URL=$redis_url" >> $FILE
  echo "REDIS_PORT=$redis_port" >> $FILE
  echo "PGUSER=$TF_VAR_dbuser" >> $FILE
  echo "PGPASSWORD=$TF_VAR_dbpassword" >> $FILE
  echo "RAILS_MAX_THREADS=$RAILS_MAX_THREADS_TESTING" >> $FILE
  echo "RECAPTCHA_TOKEN=$RECAPTCHA_TOKEN_TESTING" >> $FILE
  echo "SECRET_KEY=$SECRET_KEY_TESTING" >> $FILE
  echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_TESTING" >> $FILE
  echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_TESTING" >> $FILE
  echo "S3_BUCKET=$S3_BUCKET_TESTING" >> $FILE
  echo "SECRET_KEY_BASE=$SECRET_KEY_BASE_TESTING" >> $FILE
  echo "PUBLISHABLE_KEY=$PUBLISHABLE_KEY_TESTING" >> $FILE
  echo "STRIPE_SECRET_KEY=$STRIPE_SECRET_KEY_TESTING" >> $FILE
  echo "ZOOM_API_KEY=$ZOOM_API_KEY_TEESTING" >> $FILE
  echo "ZOOM_API_SECRET=$ZOOM_API_SECRET_TESTING" >> $FILE
  echo "DISCOURSE_SECRET=$DISCOURSE_SECRET" >> $FILE
  echo "DISCOURSE_URL_SSO=$DISCOURSE_URL_SSO" >> $FILE
  echo "DISCOURSE_URL=$DISCOURSE_URL" >> $FILE
  echo "BUGSNAG_KEY=$BUGSNAG_KEY_TESTING" >> $FILE
  echo "BUGSNAG_RELEASE_STAGE=staging" >> $FILE
  echo "MANDRILL_API_KEY=$MANDRILL_TEST_KEY" >> $FILE
  echo "MARKETING_EMAILS=$MARKETING_EMAILS" >> $FILE
  echo "LINKS_EMAILS=$LINKS_EMAILS" >> $FILE

elif [[ $CIRCLE_BRANCH =~ 'dev' ]]; then
	echo 'dev'
  FILE=.env
  touch $FILE
  echo "ASSET_HOST=$public_ip" >> $FILE
  echo "PGHOST=$db_address" >> $FILE
  echo "PG_PORT=$db_port" >> $FILE
  echo "NGINX_PORT=80" >> $FILE
  echo "HTTPS_NGINX_PORT=443" >> $FILE
  echo "APP_HOST=$public_ip" >> $FILE
  echo "RAILS_ENV=dev" >> $FILE
  echo "REDIS_URL=$redis_url" >> $FILE
  echo "REDIS_PORT=$redis_port" >> $FILE
  echo "PGUSER=$TF_VAR_dbuser" >> $FILE
  echo "PGPASSWORD=$TF_VAR_dbpassword" >> $FILE
  echo "RAILS_MAX_THREADS=$RAILS_MAX_THREADS_TESTING" >> $FILE
  echo "RECAPTCHA_TOKEN=$RECAPTCHA_TOKEN_TESTING" >> $FILE
  echo "SECRET_KEY=$SECRET_KEY_TESTING" >> $FILE
  echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_TESTING" >> $FILE
  echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_TESTING" >> $FILE
  echo "S3_BUCKET=$S3_BUCKET_TESTING" >> $FILE
  echo "SECRET_KEY_BASE=$SECRET_KEY_BASE_TESTING" >> $FILE
  echo "PUBLISHABLE_KEY=$PUBLISHABLE_KEY_TESTING" >> $FILE
  echo "STRIPE_SECRET_KEY=$STRIPE_SECRET_KEY_TESTING" >> $FILE
  echo "ZOOM_API_KEY=$ZOOM_API_KEY_TEESTING" >> $FILE
  echo "ZOOM_API_SECRET=$ZOOM_API_SECRET_TESTING" >> $FILE
  echo "DISCOURSE_SECRET=$DISCOURSE_SECRET" >> $FILE
  echo "DISCOURSE_URL_SSO=$DISCOURSE_URL_SSO" >> $FILE
  echo "DISCOURSE_URL=$DISCOURSE_URL" >> $FILE
  echo "BUGSNAG_KEY=$BUGSNAG_KEY_TESTING" >> $FILE
  echo "BUGSNAG_RELEASE_STAGE=dev" >> $FILE
  echo "MANDRILL_API_KEY=$MANDRILL_TEST_KEY" >> $FILE
  echo "MARKETING_EMAILS=$MARKETING_EMAILS" >> $FILE
  echo "LINKS_EMAILS=$LINKS_EMAILS" >> $FILE

fi
